# Generated by Django 3.1.7 on 2021-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0003_auto_20210510_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='after_predict',
            field=models.FileField(default=1, upload_to='predict_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='predictImage',
        ),
    ]
